# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1127, 845)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.EnterBD = QtWidgets.QTabWidget(self.tab_1)
        self.EnterBD.setGeometry(QtCore.QRect(0, 30, 1101, 791))
        self.EnterBD.setObjectName("EnterBD")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.widget = QtWidgets.QWidget(self.tab_11)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 1101, 731))
        self.widget.setObjectName("widget")
        self.Button1 = QtWidgets.QPushButton(self.widget)
        self.Button1.setGeometry(QtCore.QRect(450, 690, 241, 31))
        self.Button1.setObjectName("Button1")
        self.EnterBD.addTab(self.tab_11, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 1101, 731))
        self.widget_2.setObjectName("widget_2")
        self.Button2 = QtWidgets.QPushButton(self.widget_2)
        self.Button2.setGeometry(QtCore.QRect(450, 690, 241, 31))
        self.Button2.setObjectName("Button2")
        self.EnterBD.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widget_3 = QtWidgets.QWidget(self.tab_3)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 1101, 731))
        self.widget_3.setObjectName("widget_3")
        self.Button3 = QtWidgets.QPushButton(self.widget_3)
        self.Button3.setGeometry(QtCore.QRect(450, 690, 241, 31))
        self.Button3.setObjectName("Button3")
        self.EnterBD.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget_4 = QtWidgets.QWidget(self.tab_4)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 1101, 741))
        self.widget_4.setObjectName("widget_4")
        self.Button4 = QtWidgets.QPushButton(self.widget_4)
        self.Button4.setGeometry(QtCore.QRect(450, 690, 241, 31))
        self.Button4.setObjectName("Button4")
        self.EnterBD.addTab(self.tab_4, "")
        self.EnterBD_2 = QtWidgets.QPushButton(self.tab_1)
        self.EnterBD_2.setGeometry(QtCore.QRect(0, 0, 241, 31))
        self.EnterBD_2.setObjectName("EnterBD_2")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.tabWidget.addTab(self.tab_21, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.EnterBD.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button1.setText(_translate("MainWindow", "Побудувати графік"))
        self.EnterBD.setTabText(self.EnterBD.indexOf(self.tab_11), _translate("MainWindow", "Температурні умови"))
        self.Button2.setText(_translate("MainWindow", "Побудувати графік"))
        self.EnterBD.setTabText(self.EnterBD.indexOf(self.tab_2), _translate("MainWindow", "Тривалість температурних режимів"))
        self.Button3.setText(_translate("MainWindow", "Побудувати графік"))
        self.EnterBD.setTabText(self.EnterBD.indexOf(self.tab_3), _translate("MainWindow", "Троянда вітрів "))
        self.Button4.setText(_translate("MainWindow", "Побудувати графік"))
        self.EnterBD.setTabText(self.EnterBD.indexOf(self.tab_4), _translate("MainWindow", "Тривалість режимів вітрової активності"))
        self.EnterBD_2.setText(_translate("MainWindow", "Выберите базу данных"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Вкладка 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_21), _translate("MainWindow", "Вкладка 2"))
